import Head from 'next/head'
import styles from '../styles/Home.module.css'
import QuestionOneLine from "../сomponents/QuestionOneLine";
import QuestionChoice from "../сomponents/QuestionChoice";
import data from "../data.json"
import {useState} from "react";

const uniform = (s) =>
    s.toLowerCase().replace("ё", "е")

export default function Home() {
  const [final, setFinal] = useState(null);
  const [error, setError] = useState(null);
  const [step, setStep] = useState(null);
  const onNameInput = (name) => {
    const variants = data.filter((value) => uniform(value["ФИО"]) === uniform(name.toLowerCase()))
    console.log(variants)
    if (variants === []) {
      setError("Ты не найден, попробуй еще раз")
      return
    }
    setFinal(variants[0])
    setStep((step) => step + 1)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Добро пожаловать на сборы!
        </h1>

        <p className={styles.description}>
          Этот тест поможет определить твою группу
        </p>

        <div className={styles.grid}>
          <QuestionOneLine title="Первый вопрос" question="Твои ФИО" onInput={onNameInput}/>
          <QuestionOneLine title="Второй вопрос" question="Твой номер телефона"/>
          <QuestionOneLine title="Третий вопрос" question="Какой у тебя цвет глаз?"/>
          <QuestionOneLine title="Четвертый вопрос" question="Какое твоё любимое животное?"/>
          <QuestionChoice title="Пятый вопрос" question="Дружба или соперничество?">
            <span>Дружба</span>
            <span>Соперничество</span>
          </QuestionChoice>
          <QuestionOneLine title="Шестой вопрос" question="Какие 3 предмета ты бы взял с собой на выезд?"/>
          <QuestionOneLine title="Седьмой вопрос" question="Опиши себя одним прилагательным"/>
          <QuestionChoice title="Восьмой вопрос" question="Какой ты сегодня?">
            <span>Меланхоличный позер</span>
            <span>Дышащий творчеством артклабовец</span>
            <span>А ты?</span>
            <span>Латентный прогульщик</span>
          </QuestionChoice>
          <QuestionChoice title="Девятый вопрос" question="Для тебя страх - это преграда или мотивация?">
            <span>Преграда</span>
            <span>Мотивация</span>
          </QuestionChoice>
          <QuestionOneLine title="Десятый вопрос" question={"Продолжи фразу: \"Мир станет лучше, если...\""}/>
        </div>
      </main>
    </div>
  )
}
